apiVersion: v1
kind: ServiceAccount
metadata:
  name: clfotlp
  namespace: openshift-logging
---
# oc adm policy add-cluster-role-to-user collect-infrastructure-logs -z clfotlp -n openshift-logging
# oc adm policy add-cluster-role-to-user collect-application-logs -z clfotlp -n openshift-logging

#apiVersion: v1
#kind: Secret
#metadata:
#  name: clfotlp-secret
#  namespace: openshift-logging
#  annotations:
#    # This annotation binds the secret to the ServiceAccount
#    kubernetes.io/service-account.name: clfotlp
#type: kubernetes.io/service-account-token
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    observability.openshift.io/tech-preview-otlp-output: enabled
  name: logging
  namespace: openshift-logging
spec:
  collector:
#    resources: # < Lab specific
#      limits:
#        cpu: '6'
#        memory: 4Gi
#      requests:
#        cpu: 500m
#        memory: 64Mi
  managementState: Managed
  outputs:
    - name: otlp
      otlp:
        tuning:
          deliveryMode: AtLeastOnce
          maxRetryDuration: 20
          minRetryDuration: 5
        url: http://otel-collector.openshift-logging.svc.cluster.local:4318/v1/logs
      type: otlp
  pipelines:
    - inputRefs:
        - infrastructure
      name: otlppipeline
      outputRefs:
        - otlp
  serviceAccount:
    name: clfotlp
