apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: "2025-10-07T10:43:56Z"
      generation: 1
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/instance: observability.simplest
        app.kubernetes.io/managed-by: opentelemetry-operator
        app.kubernetes.io/name: simplest-collector-networkpolicy
        app.kubernetes.io/part-of: opentelemetry
        app.kubernetes.io/version: latest
      name: simplest-collector-networkpolicy
      namespace: observability
      ownerReferences:
        - apiVersion: opentelemetry.io/v1beta1
          blockOwnerDeletion: true
          controller: true
          kind: OpenTelemetryCollector
          name: simplest
          uid: 639243b4-46a9-4108-8381-de2d653d8b56
      resourceVersion: "201331"
      uid: 41fc1392-82b4-46f5-8fe3-2528e696eeb2
    spec:
      ingress:
        - ports:
            - port: 8888
              protocol: TCP
            - port: 4317
              protocol: TCP
            - port: 4318
              protocol: TCP
            - port: 13133
              protocol: TCP
            - port: 6831
              protocol: TCP
      podSelector:
        matchLabels:
          app.kubernetes.io/component: opentelemetry-collector
          app.kubernetes.io/instance: observability.simplest
          app.kubernetes.io/managed-by: opentelemetry-operator
          app.kubernetes.io/part-of: opentelemetry
      policyTypes:
        - Ingress
kind: List
metadata:
  resourceVersion: ""
---
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
simplest-collector              ClusterIP   10.217.4.193   <none>        4317/TCP,4318/TCP,6831/UDP   61m
simplest-collector-extension    ClusterIP   10.217.5.4     <none>        13133/TCP                    61m
simplest-collector-headless     ClusterIP   None           <none>        4317/TCP,4318/TCP,6831/UDP   61m
simplest-collector-monitoring   ClusterIP   10.217.5.95    <none>        8888/TCP                     61m
----
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.217.0.97/23"],"mac_address":"0a:58:0a:d9:00:61","gateway_ips":["10.217.0.1"],"routes":[{"dest":"10.217.0.0/22","nextHop":"10.217.0.1"},{"dest":"10.217.4.0/23","nextHop":"10.217.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.217.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.217.0.1"}],"ip_address":"10.217.0.97/23","gateway_ip":"10.217.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.217.0.97"
          ],
          "mac": "0a:58:0a:d9:00:61",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    opentelemetry-operator-config/sha256: 8eac6b533d6ca6ef6ada05f031aba3d44c5ca044a4aa3db3b4aef15930288d6e
    prometheus.io/path: /metrics
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2025-10-07T10:44:32Z"
  generateName: simplest-collector-6db5cffc8c-
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: observability.simplest
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/name: simplest-collector
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: latest
    pod-template-hash: 6db5cffc8c
  name: simplest-collector-6db5cffc8c-r7crq
  namespace: observability
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: simplest-collector-6db5cffc8c
      uid: 431ab50a-dcee-4ea9-946f-3b8999ebe101
  resourceVersion: "201479"
  uid: 3a4cb857-8db5-4bc4-8fe2-0e45377be0e0
spec:
  containers:
    - args:
        - --config=/conf/collector.yaml
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      image: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:5f31caf1f4a12cf2832ac3e84877f4fb0c856073820498c8a5be13698348c38a
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 13133
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: otc-container
      ports:
        - containerPort: 8888
          name: metrics
          protocol: TCP
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 13133
          name: port-13133
          protocol: TCP
        - containerPort: 6831
          name: port-6831
          protocol: UDP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 13133
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000680000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /conf
          name: otc-internal
        - mountPath: /etc/otelcol/
          name: sampling-strategies
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-xb6sc
          readOnly: true
  dnsConfig: {}
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
    - name: simplest-collector-dockercfg-qkxrj
  nodeName: crc
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000680000
    seLinuxOptions:
      level: s0:c26,c15
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: simplest-collector
  serviceAccountName: simplest-collector
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - configMap:
        defaultMode: 420
        items:
          - key: collector.yaml
            path: collector.yaml
        name: simplest-collector-8eac6b53
      name: otc-internal
    - configMap:
        defaultMode: 420
        items:
          - key: sampling_strategies.json
            path: sampling_strategies.json
        name: simplest-sampling-strategies
      name: sampling-strategies
    - name: kube-api-access-xb6sc
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
          - configMap:
              items:
                - key: service-ca.crt
                  path: service-ca.crt
              name: openshift-service-ca.crt
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-10-07T10:44:34Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-10-07T10:44:33Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-10-07T10:44:35Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-10-07T10:44:35Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-10-07T10:44:33Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: cri-o://b73294cfd1e7c165fb4df041d795fc5f3c994799e8d840da427fe94c34bcb1bf
      image: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:5f31caf1f4a12cf2832ac3e84877f4fb0c856073820498c8a5be13698348c38a
      imageID: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:5f31caf1f4a12cf2832ac3e84877f4fb0c856073820498c8a5be13698348c38a
      lastState: {}
      name: otc-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-10-07T10:44:33Z"
      volumeMounts:
        - mountPath: /conf
          name: otc-internal
        - mountPath: /etc/otelcol/
          name: sampling-strategies
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-xb6sc
          readOnly: true
          recursiveReadOnly: Disabled
  hostIP: 192.168.126.11
  hostIPs:
    - ip: 192.168.126.11
  phase: Running
  podIP: 10.217.0.97
  podIPs:
    - ip: 10.217.0.97
  qosClass: BestEffort
  startTime: "2025-10-07T10:44:33Z"